name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.1
      with:

        cli: 1.10.1.693
        lein: 2.9.1
        boot: 2.8.3
        clj-kondo: 2022.05.31
        cljfmt: 0.10.2
        cmd-exe-workaround: 'latest'
        zprint: 1.2.3

    - name: Install dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test
